# Docker Compose configuration for home-ip-notifier development environment
# This file sets up the necessary services for development and testing
version: "3.8"

services:
  # Go development container with the project code mounted
  golang:
    image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_24
    volumes:
      - ..:/app # Mount the project directory into the container
    working_dir: /app
    command: tail -f /dev/null # Keep container running
    environment:
      - REDIS_IP=172.17.0.20 # Set Redis IP for testing
    networks:
      home-ip-notifier-net:
        ipv4_address: 172.17.0.10

  # RabbitMQ server for message broker testing
  rabbitmq:
    image: registry.windmaker.net:5005/a-castellano/limani/base_rabbitmq_server
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # RabbitMQ management interface port
    networks:
      home-ip-notifier-net:
        ipv4_address: 172.17.0.30

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      home-ip-notifier-net:
        ipv4_address: 172.17.0.20

# Custom network configuration for service communication
networks:
  home-ip-notifier-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16 # Private subnet for service communication
